### ISSUE TITLE
MathJax not loading quick enough from CDN when previewing

### ISSUE THREAD

**Issue by Dahquim** [cgkineo/adapt-mathJax#1]
When using the MathJax plugin, and previewing locally the script is not retrieved form the CDN quick enough. This leads to MathJax content not being processed on the page.

**Comment by brian-learningpool** [comment]
I'm seeing a similar intermittent timing issue which manifests itself as:
`adapt-mathJax.js:32 Uncaught TypeError: Cannot read property 'Queue' of undefined`
And sometimes:
`Cannot read property 'Init' of undefined`

**Comment by brian-learningpool** [comment]
@Dahquim, I've made a PR which corrects this for me (see #2).  

Would you  be able to give it a test?
