### ISSUE TITLE
MathJax CDN is closed

### ISSUE THREAD

**Issue by chrisgillison** [cgkineo/adapt-mathJax#3]
"_src" in config.json should be updated to "_src": "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js"

[https://www.mathjax.org/cdn-shutting-down/]

**Comment by tomgreenfield** [comment]
Thanks – resolved in https://github.com/cgkineo/adapt-mathJax/commit/ff0712e2414c0e358a46a3ddee2676779642ed8d.
