### ISSUE TITLE
Using in AT requires different syntax

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-mathJax#4]
For this to work in the AT you need to use a single forward slash instead of two.

It would be useful for AT users to have a note of this on the github page!

**Comment by oliverfoster** [comment]
could you give an example? @simondate

**Comment by tomgreenfield** [comment]
It does already say this...
> * When directly editing in the authoring tool, backslashes do not have to be escaped with an additional backslash `\`.

**Comment by simondate** [comment]
My mistake! But maybe it would be more obvious with bold text or at the bottom as a limitation?

**Comment by oliverfoster** [comment]
This is a limitation of json+javascript, not so much a limitation of the plugin.

To prove the point, try typing ``"\\"`` into your browser console. You'll notice that ``"\\"`` == ``"\"``
![image](https://user-images.githubusercontent.com/7974663/33604105-b51006c4-d9ac-11e7-9dac-aaf21ab3000b.png)

This issue cannot be overcome with clearer documentation as is evident by this ticket and the vast amount of information already available on the internet about string escaping.  it requires a fundamental understanding of string escaping and for each person to stumble over it in their own way. The concept is reasonably clear in theory, worse in practice and rarely explained between developers.

Try these links:
https://en.wikipedia.org/wiki/Escape_character  
https://stackoverflow.com/questions/42228504/how-do-i-escape-double-backslashes-for-mathjax  
http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents  
https://stackoverflow.com/questions/21082961/json-string-escaping-mathjax
